# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cmdb', '0002_auto_20191209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='管理IP'),
        ),
    ]
