# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_cmdb', '0006_auto_20191209_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='cpu_core_count',
            new_name='cpu_physical_count',
        ),
        migrations.AlterField(
            model_name='server',
            name='asset',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_cmdb.Asset'),
        ),
    ]
