# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-10 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cmdb', '0009_auto_20191209_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='board_manufacturer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主板厂商'),
        ),
        migrations.AddField(
            model_name='server',
            name='board_model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主板型号'),
        ),
        migrations.AddField(
            model_name='server',
            name='board_sn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='主板SN号'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, '其它'), (1, '硬件变更'), (2, '新增配件'), (3, '设备下线'), (4, '设备上线'), (5, '定期维护'), (6, '业务上线\\更新\\变更')], default=2, verbose_name='事件类型'),
        ),
    ]
