# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-10 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_cmdb', '0011_auto_20191210_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='disk',
            name='asset',
        ),
        migrations.DeleteModel(
            name='Disk',
        ),
    ]
