# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_cmdb', '0012_auto_20191210_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, max_length=64, null=True, verbose_name='所在插槽位')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='磁盘型号')),
                ('capacity', models.FloatField(blank=True, null=True, verbose_name='磁盘容量(GB)')),
                ('interface_type', models.CharField(default='unknown', max_length=32, verbose_name='接口类型')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_cmdb.Asset')),
            ],
            options={
                'verbose_name': '硬盘',
            },
        ),
    ]
