# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-12-10 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_cmdb', '0013_disk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='board_manufacturer',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='主板厂商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='board_model',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='主板型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='board_sn',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='主板SN号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_model',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='CPU型号'),
        ),
    ]
